package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// Chat exports are filed one directory per month:
//
//	agent-chats/
//	  index.html                     ← landing page, always at the root
//	  assets/viewer.css, viewer.js   ← agent-chat-owned, one copy for the archive
//	  2026-08/
//	    15-01-some-title.md
//	    assets/2026-08-15-01-1-{sha12}.png
//
// A year of daily chats is then 12 directories instead of one flat pile of
// several hundred files.
//
// Two rules keep the split from breaking anything:
//
//  1. Attachment *basenames* keep their full `{YYYY-MM-DD}-{NN}-{n}-{sha12}`
//     form even though they now sit in a month directory. The link inside the
//     .md stays `./assets/{basename}`, so migrating an old export is a pure
//     `git mv` — no rewriting of committed markdown.
//  2. viewer.css / viewer.js stay in the root `assets/`. They are rewritten on
//     every export; a per-month copy would mean twelve churning duplicates a
//     year and stale copies rotting in old months. index.html sits beside
//     them, so its `./assets/viewer.css` link is unaffected.
//
// The flat layout is still read everywhere (scanChatExports returns both), so
// an archive that has not been migrated keeps working — see migrateChatLogs.

// monthDirRE matches a month directory name, "YYYY-MM".
var monthDirRE = regexp.MustCompile(`^\d{4}-\d{2}$`)

// mdMonthNameRE parses an exported chat filename inside a month directory:
// {DD}-{NN}-{slug}.md with NN 2 or 3 digits (matching nextDailyIndex).
var mdMonthNameRE = regexp.MustCompile(`^(\d{2})-(\d{2,3})-(.+)\.md$`)

// chatLogLayout selects where a NEW export is written. Reading is always
// layout-blind — scanChatExports returns both shapes no matter what this is set
// to — so an archive holding a mixture is listed, resumed and numbered
// correctly either way.
//
// The default is layoutAuto: a new export follows the archive it lands in. Once
// any chat is filed in a month directory -- one person ran migrate-chatlogs, or
// set the layout to month, and committed the result -- every copy that reads
// that archive files its next chat by month too, with nothing to configure per
// machine. An archive with no month-filed chat stays flat, which is what keeps
// it visible to copies too old to see month directories (such a copy
// regenerating index.html drops every file it cannot see out of the listing).
// "flat" and "month" pin the layout regardless of what the archive holds.
type chatLogLayout int

const (
	// layoutAuto writes by month if the archive already has a month-filed
	// chat, flat otherwise.
	layoutAuto chatLogLayout = iota
	// layoutFlat writes agent-chats/{YYYY-MM-DD}-{NN}-{slug}.md.
	layoutFlat
	// layoutMonth writes agent-chats/{YYYY-MM}/{DD}-{NN}-{slug}.md.
	layoutMonth
)

// chatLogLayoutSetting is resolved once at startup from -chatlog-layout /
// AGENT_CHAT_CHATLOG_LAYOUT (see parseChatLogLayout).
var chatLogLayoutSetting = layoutAuto

// parseChatLogLayout resolves the layout from the flag value (empty when the
// flag was not given) falling back to the env var, then to layoutAuto. An
// unrecognised value is an error rather than a silent default: writing chats
// somewhere other than intended is not something to discover months later.
func parseChatLogLayout(flagVal, envVal string) (chatLogLayout, error) {
	v := strings.TrimSpace(flagVal)
	if v == "" {
		v = strings.TrimSpace(envVal)
	}
	switch strings.ToLower(v) {
	case "", "auto":
		return layoutAuto, nil
	case "flat":
		return layoutFlat, nil
	case "month":
		return layoutMonth, nil
	default:
		return layoutAuto, fmt.Errorf("unknown chat-log layout %q: want \"auto\", \"flat\" or \"month\"", v)
	}
}

// chatLogGitignoreSetting is resolved once at startup from -chatlog-gitignore /
// AGENT_CHAT_CHATLOG_GITIGNORE (see parseChatLogGitignore).
var chatLogGitignoreSetting = true

// parseChatLogGitignore resolves whether a new archive gets a .gitignore for
// its generated files, from the flag value (empty when the flag was not
// given) falling back to the env var, then to on.
func parseChatLogGitignore(flagVal, envVal string) (bool, error) {
	v := strings.TrimSpace(flagVal)
	if v == "" {
		v = strings.TrimSpace(envVal)
	}
	switch strings.ToLower(v) {
	case "", "on", "true", "1", "yes":
		return true, nil
	case "off", "false", "0", "no":
		return false, nil
	default:
		return true, fmt.Errorf("unknown chat-log gitignore setting %q: want \"on\" or \"off\"", v)
	}
}

// archiveGitignore is written into a newly created archive root. Anchored
// patterns: assets/ also holds the chats' attachments, which nothing can
// regenerate and which must stay tracked.
const archiveGitignore = `# Written by agent-chat when it created this directory. These three files are
# regenerated by agent-chat itself (every start and every export), so they are
# kept out of git. To commit them instead, delete this file, or start
# agent-chat with -chatlog-gitignore=off before it creates the directory.
/index.html
/assets/viewer.css
/assets/viewer.js
`

// ensureArchiveDir creates the archive root, and — only when this call is what
// brings it into existence, inside a git work tree — a .gitignore for the
// generated files. An archive that already exists is never touched: its
// generated files are usually tracked, where an ignore rule changes nothing,
// and its team may still run copies whose chatlog_close hands those paths to
// `git add`, which refuses an ignored one. Switching an existing archive is a
// deliberate act (add the file, `git rm --cached` the three).
func ensureArchiveDir(root string) error {
	_, statErr := os.Stat(root)
	if err := os.MkdirAll(root, 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", root, err)
	}
	if !os.IsNotExist(statErr) || !chatLogGitignoreSetting || !inGitWorkTree(root) {
		return nil
	}
	if err := os.WriteFile(filepath.Join(root, ".gitignore"), []byte(archiveGitignore), 0644); err != nil {
		return fmt.Errorf("write %s/.gitignore: %w", root, err)
	}
	return nil
}

// inGitWorkTree reports whether dir is inside a git work tree. No git, or no
// repo, is simply false.
func inGitWorkTree(dir string) bool {
	cmd := exec.Command("git", "rev-parse", "--is-inside-work-tree")
	cmd.Dir = dir
	out, err := cmd.Output()
	return err == nil && strings.TrimSpace(string(out)) == "true"
}

// archiveFiledByMonth reports whether root already holds at least one chat in
// a month directory. An empty `2026-08/` does not count: only a filed chat is
// evidence that someone chose the month layout for this archive.
func archiveFiledByMonth(root string) bool {
	entries, err := os.ReadDir(root)
	if err != nil {
		return false
	}
	for _, de := range entries {
		if de.IsDir() && monthDirRE.MatchString(de.Name()) && len(scanMonthDir(root, de.Name())) > 0 {
			return true
		}
	}
	return false
}

// monthOf returns the "YYYY-MM" part of a "YYYY-MM-DD" date, or "" if date is
// not shaped like one. Callers treat "" as "keep it flat in the root", which
// is what makes a malformed date degrade to the old layout instead of creating
// a junk directory.
func monthOf(date string) string {
	if len(date) != len("2006-01-02") {
		return ""
	}
	month := date[:7]
	if !monthDirRE.MatchString(month) {
		return ""
	}
	return month
}

// dayOf returns the "DD" part of a "YYYY-MM-DD" date, or "" if date is not
// shaped like one.
func dayOf(date string) string {
	if monthOf(date) == "" {
		return ""
	}
	return date[8:]
}

// chatMonthDir is the directory an export for date belongs in: root/{YYYY-MM},
// falling back to root itself for a date that isn't one.
func chatMonthDir(root, date string) string {
	month := monthOf(date)
	if month == "" {
		return root
	}
	return filepath.Join(root, month)
}

// chatAssetsDir is where an export for date keeps its image attachments.
func chatAssetsDir(root, date string) string {
	return filepath.Join(chatMonthDir(root, date), "assets")
}

// exportAssetsDir is where one export's attachments live: always the `assets/`
// directory beside the .md itself. That is the same rule the `./assets/…`
// links inside the markdown follow, so it holds for a month-filed export and
// for a legacy flat one alike.
func exportAssetsDir(mdPath string) string {
	return filepath.Join(filepath.Dir(mdPath), "assets")
}

// viewerAssetsDir is where the archive's viewer.css / viewer.js live — always
// the root assets/, never a month directory (see the file comment).
func viewerAssetsDir(root string) string {
	return filepath.Join(root, "assets")
}

// chatMDName is the basename of an export inside its month directory:
// `{DD}-{NN}-{slug}.md`. A date that isn't one keeps the full flat name, so
// nothing can collide across months.
func chatMDName(date, idx, slug string) string {
	if day := dayOf(date); day != "" {
		return fmt.Sprintf("%s-%s-%s.md", day, idx, slug)
	}
	return fmt.Sprintf("%s-%s-%s.md", date, idx, slug)
}

// chatMDPath is the full path an export for (date, idx, slug) is written to.
func chatMDPath(root, date, idx, slug string) string {
	return filepath.Join(chatMonthDir(root, date), chatMDName(date, idx, slug))
}

// renamedMDPath is where set_chat_title moves an export to. It renames the
// file *in place* — a legacy flat export keeps its full-date basename and its
// place in the root, a month-filed one keeps its month directory. A retitle
// must never also relocate a file that may already be committed; migration is
// migrateChatLogs' job and nothing else's.
func renamedMDPath(oldPath, root, date, idx, slug string) string {
	dir := filepath.Dir(oldPath)
	if filepath.Clean(dir) == filepath.Clean(root) {
		return flatMDPath(dir, date, idx, slug)
	}
	return filepath.Join(dir, chatMDName(date, idx, slug))
}

// flatMDPath is the pre-month-layout location of an export:
// root/{YYYY-MM-DD}-{NN}-{slug}.md.
func flatMDPath(root, date, idx, slug string) string {
	return filepath.Join(root, fmt.Sprintf("%s-%s-%s.md", date, idx, slug))
}

// exportMDPath is where a NEW export goes, honouring chatLogLayoutSetting.
// Migration deliberately does not use it: migrateChatLogs always targets the
// month layout, because moving files there is the whole point of running it.
func exportMDPath(root, date, idx, slug string) string {
	if chatLogLayoutSetting == layoutMonth ||
		(chatLogLayoutSetting == layoutAuto && archiveFiledByMonth(root)) {
		return chatMDPath(root, date, idx, slug)
	}
	return flatMDPath(root, date, idx, slug)
}

// chatAssetPrefix is the shared basename prefix of every attachment belonging
// to one export. It keeps the full date even inside a month directory, so the
// `./assets/…` links in already-committed markdown survive migration untouched.
func chatAssetPrefix(date, idx string) string {
	return date + "-" + idx + "-"
}

// chatExportFile is one exported chat found on disk, in either layout.
type chatExportFile struct {
	Path   string // absolute path to the .md
	Rel    string // root-relative, slash-separated: "2026-08/15-01-x.md"
	Date   string // "YYYY-MM-DD"
	Index  string // "01" … "999"
	Slug   string
	Legacy bool // still sitting flat in the root, awaiting migration
}

// scanChatExports returns every export under root in an unspecified order,
// reading both layouts: `{YYYY-MM}/{DD}-{NN}-{slug}.md` and the legacy flat
// `{YYYY-MM-DD}-{NN}-{slug}.md`. Anything that doesn't match either shape (a
// hand-written notes.md, index.html, the assets directories) is skipped. An
// unreadable root returns nil — every caller treats that as "no exports".
func scanChatExports(root string) []chatExportFile {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil
	}
	var out []chatExportFile
	for _, de := range entries {
		if de.IsDir() {
			if !monthDirRE.MatchString(de.Name()) {
				continue
			}
			out = append(out, scanMonthDir(root, de.Name())...)
			continue
		}
		m := mdExportNameRE.FindStringSubmatch(de.Name())
		if m == nil {
			continue
		}
		out = append(out, chatExportFile{
			Path:   filepath.Join(root, de.Name()),
			Rel:    de.Name(),
			Date:   m[1],
			Index:  m[2],
			Slug:   m[3],
			Legacy: true,
		})
	}
	return out
}

// scanMonthDir returns the exports inside root/month.
func scanMonthDir(root, month string) []chatExportFile {
	entries, err := os.ReadDir(filepath.Join(root, month))
	if err != nil {
		return nil
	}
	var out []chatExportFile
	for _, de := range entries {
		if de.IsDir() {
			continue
		}
		m := mdMonthNameRE.FindStringSubmatch(de.Name())
		if m == nil {
			continue
		}
		out = append(out, chatExportFile{
			Path:  filepath.Join(root, month, de.Name()),
			Rel:   month + "/" + de.Name(),
			Date:  month + "-" + m[1],
			Index: m[2],
			Slug:  m[3],
		})
	}
	return out
}

// manifestRef renders an export's root-relative path the way index.html's
// MANIFEST spells it: "./2026-08/15-01-x.md". A path outside root falls back to
// its basename rather than emitting a "../" link the viewer could not fetch.
func manifestRef(root, mdPath string) string {
	rel, err := filepath.Rel(root, mdPath)
	if err != nil || strings.HasPrefix(rel, "..") {
		return "./" + filepath.Base(mdPath)
	}
	return "./" + filepath.ToSlash(rel)
}
